logging:
  file:
    name: log/springbootelasticsearch.log

server:
  port: 8001

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      repositories:
        enabled: true

elasticsearch:
  host: http://localhost:9200



